name: tp0
services:
  server:
    container_name: server
    image: server:latest
    entrypoint: python3 server/main.py
    environment:
      - LOGGING_LEVEL=DEBUG
    networks:
      - testing_net
    volumes:
      - ./server:/server

  client1:
    container_name: client1
    image: client:latest
    entrypoint: /client
    environment:
        - CLI_ID=1
    networks:
        - testing_net
    depends_on:
        - server
    volumes:
      - ./client:/config

networks:
  testing_net:
    ipam:
      driver: default