name: tp0
services:
  server:
    container_name: server
    image: server:latest
    entrypoint: python3 server/main.py
    environment:
      - PYTHONUNBUFFERED=1
      - LOGGING_LEVEL=DEBUG
    networks:
      - testing_net
    volumes:
      - ./server:/server

  client0:
    container_name: client0
    image: client:latest
    entrypoint: /client
    environment:
        - CLI_LOG_LEVEL=DEBUG
        - CLI_ID=0
        - FILE=/agency-1.csv
    networks:
        - testing_net
    depends_on:
        - server
    volumes:
      - ./client:/config

  client1:
    container_name: client1
    image: client:latest
    entrypoint: /client
    environment:
        - CLI_LOG_LEVEL=DEBUG
        - CLI_ID=1
        - FILE=/agency-2.csv
    networks:
        - testing_net
    depends_on:
        - server
    volumes:
      - ./client:/config

  client2:
    container_name: client2
    image: client:latest
    entrypoint: /client
    environment:
        - CLI_LOG_LEVEL=DEBUG
        - CLI_ID=2
        - FILE=/agency-3.csv
    networks:
        - testing_net
    depends_on:
        - server
    volumes:
      - ./client:/config

networks:
  testing_net:
    ipam:
      driver: default
