name: tp0
services:
  server:
    container_name: server
    image: server:latest
    entrypoint: python3 server/main.py
    environment:
      - PYTHONUNBUFFERED=1
      - LOGGING_LEVEL=DEBUG
    networks:
      - testing_net
    volumes:
      - ./server:/server

  client0:
    container_name: client0
    image: client:latest
    entrypoint: /client
    environment:
        - CLI_LOG_LEVEL=DEBUG
        - CLI_ID=0
        - DNI=30904465
        - NOMBRE=Santiago Lionel
        - APELLIDO=Lorca
        - NACIMIENTO=1999-03-17
        - NUMERO=7574
    networks:
        - testing_net
    depends_on:
        - server
    volumes:
      - ./client:/config

networks:
  testing_net:
    ipam:
      driver: default
      config:
        - subnet: 172.25.125.0/24